version: "3.7"

services:
  frontend:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
  backend:
    image: node:16.15.0
    volumes:
      - ./backend/:/app
    working_dir: /app
    user: node
    restart: unless-stopped
    command: ["bash", "start.sh"]
  nodemon:
    image: node:16.15.0
    volumes:
      - ./nodemon:/app
    working_dir: /app
    user: node
    command: ["bash", "start.sh"]